### ISSUE TITLE
Review applications page and generated reports should include seat names

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#115]
When selecting the seats to include in the generated report on the view application page, the seat name should be included. 

If the seat names are too long, they can be truncated to preserve the layout

The seat name should also be included on the generated report under the "Requirements" section. 

[https://bloomington.in.gov/onboard/committees/applications?committee_id=5](url)

**Comment by inghamn** [comment]
There's already some layout work we need to do to accommodate the seats display.  We might need to just put the seat information above the applicants, instead of trying to do them side by side.

![screen](https://cloud.githubusercontent.com/assets/630282/13709202/a384f664-e780-11e5-9dd7-d6be56a0cac2.png)

**Comment by charlesbrandt** [comment]
Dan, if you have a chance, I'd be interested to hear your opinion on this or see any suggestions.
