### ISSUE TITLE
Corrupt resume uploads

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#143]
When trying to open some of the resumes these applicants have uploaded, it appears they have been corrupted. The files are often several hundred pages of Wingdings-type characters. This error has affected about half the resumes that have been uploaded to OnBoard.

**Comment by wolfmj** [comment]
Here are a few examples:  Claudia Viloria's resume for the Commission on Hispanic and Latino Affairs

[Resume_Claudia_Viloria_HLC.pdf](https://github.com/City-of-Bloomington/OnBoard/files/401654/Resume_Claudia_Viloria_HLC.pdf)

Coleman Burnett for the Commission on Sustainability

[Coleman_Burnett_resume_May2016 (1).pdf](https://github.com/City-of-Bloomington/OnBoard/files/401659/Coleman_Burnett_resume_May2016.1.pdf)

**Comment by inghamn** [comment]
It turns out, I was just converting all  files, no matter what, into PDF.  I guess I was thinking that if the file were already a PDF, then OpenOffice would just do a no-op.  However, OpenOffice was re-encoding the PDF files, causing corruption.

I did a quick update to check if the user gave the file a .pdf extensions, and I don't try to convert those.
