### ISSUE TITLE
Apply permissions per committee

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#244]
Currently, users added to the system have global permissions to all boards and commissions based on the role that was applied. This makes sense for admin level roles like "Staff" who handle appointments for all commissions centrally. (Side note: should we rename it to "Appointer"?)

For the other roles (Applicants-view-only, meetingFileUploader, Liaison), these could be applied at the commission level. We already have a mechanism to indicate who the Liaisons are for a given commission (departmental & legal). This could be extended to include other roles. 

This approach would have many benefits: 
   - ensure that the liaison/file_uploaders/etc lists for a commission stay up to date
   - prevent accidental update of information on other commissions (narrowed permissions)
   - expand the city staff points-of-contact for a commission (e.g. meetingFileUploader may be able to help with questions in addition to official liaisons)

We may want to explore automatically removing liaison roles when a user account is removed.

**Comment by inghamn** [comment]
The Applicants-View-only and meetingFileUploader roles do not contain people that are directly linked to a committee.  In order to limiting people in those roles to particular committees, we'll need to build something similar to what we have for Liaisons.

It's just that the being a Liaison was a thing long before we had a role for those people.   I'm not sure what we call the people who are just responsible for uploading meeting files.

It would probably be useful to audit all those people and see if they might actually be Liaisons.

**Comment by inghamn** [comment]
After implementing per-comittee checks and the new department checks, it's turning out that the department permissions are more useful.
