### ISSUE TITLE
Create new account functionality broken

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#261]
This issue may be related to permission changes that happened in the Directory application. 

When trying to add a new user to Onboard, I receive the following message:

<img width="1316" alt="screen shot 2019-02-15 at 8 45 01 am" src="https://user-images.githubusercontent.com/2225624/52860794-7d170d80-30fe-11e9-92b7-3bd358c69500.png">

**Comment by inghamn** [comment]
Directory recently changed the way it checks permission for giving out information. Access to restricted information now requires authentication.  Since we don't have a way to do authenticated web service calls, we're not able to find out information for people in AD that are not publically viewable.
