### ISSUE TITLE
End date should not be required when creating first term

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#56]
When creating the initial term for a given seat, the start and end date are requested.
However, the end date is validated against the term length configured for the board. It would be easier to calculate this attribute server side, rather than showing:

   Sorry
   invalidEndDate

**Comment by charlesbrandt** [comment]
Clarification... I don't think it even needs an input field.

**Comment by inghamn** [comment]
Without it being a required field, I have to ask for an endDate.

The term length cannot be a required field for committees.  Committees might not even have seats which have terms.  It could, however, be a per-seat setting, which could then be required for termed seats.

I could also make it a global setting.  Well, it technically is global right now, since it's hard coded.  But I can easily move that value into the configuration.inc
